server:
  port: 8082

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    name: test
    url: jdbc:mysql://127.0.0.1:3306/xmall?serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    thymeleaf:
      cache: false;
  dubbo:
    application:
      id: pmall-goods
      name: pmall-goods
    registry:
      address: zookeeper://127.0.0.1:2181
    protocol:
      id: dubbo
      name: dubbo
      port: 20882
      status: server
    #scan: com.sj.pmallgoods.Service.impl
  #aop:
    #proxy-target-class: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sj.pmallgoods.api.entity