server:
  port: 8081
#应用名称
spring:
  thymeleaf:
    cache: false #页面热加载
  dubbo:
    application:
      id: pmall-front
      name: pmall-front
      #注册中心地址
    protocol:
      name: dubbo
    registry:
      address: zookeeper://127.0.0.1:2181
    #调用dubbo组件扫描的项目路径
    scan: com.sj.pmallfront.service

    #检查服务是否可用默认为true，不可用时抛出异常，阻止spring初始化，为方便部署，可以改成false
    consumer:
       check: false
       timeout: 30000
  rabbitmq:
    virtual-host: /
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    listener:
      concurrency: 10
      max-concurrency: 20
      prefetch: 5
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
    #连接超时时间（毫秒）
    timeout: 1000
  #aop:
    #proxy-target-class: true
mq:
 env: pmall
user:
  order:
    queue:
      name: ${mq.env}.user.order.queue
    exchange:
      name: ${mq.env}.user.order.exchange
    routing:
      key:
        name: ${mq.env}.user.order.routing.key


